travis:
  secure:
    BINSTAR_TOKEN: GGuLGKZLur04xK3XJstk1N4bDmXWcV7ucBqChv3roB+iA+TM8TRd2YeHJcYEL7IfFolzC+Jh7qgNUApfvkg9dNgzo040lSrl0u5MCDeYbMbssdNaTtW9+xoeZAcOLnKte8AO8Fzrtfa4Kes88/NGbD04qFJWaXc5RIcR/lsPgionTtYbbHYr5ooG1YR42l0W8lrxk+eqozowdGxEJma7xUvoijwfTrW9xMccF+ok9aW5TvfeSgOI0cCxbBw656vV23lzaMMKlUkh7zpm7miVDLAPzZU/XSHGdZRHyOVMHP3K3fj7ZX+5Y8X3H6gYrvxAhrxOwtsce5a5CeDVZy7Og70L3S1OHpHXfK4oeY4smLFmcaVZnurD2aDJHz66HS8bvIRC/R+7vs+AgmKyQfQWsKN+E8PQxOdewCzKPzRyuMLlYt96/ildIoZ9INjgKjD+UlAhsyUWBr8T3txxIYLrimVqy3+3GRmoGn140A+dVNUw9BMB/0l+M9HJ3WHCeuWd382IyYDpHs0kULlIq87IQgB5Xs2+MSPByoIpDkb62HlH7tpRYc0MqC+6IVT4+uA144ydcW0Ln9eayj2BHLqSO/itTQ2lJTf0IgkA3lWVDRge6se3RA5QySu9oYKMQqEeD7jgHgPI0UD+BPdUDoEKfNF1+iIGJx4Hb1PVnHKY+Fg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
